### ISSUE TITLE
The page is not redirecting to any other page 

### ISSUE THREAD

**Issue by tushargupta1504** [tushargupta1504/Medical-Website#101]
Make all the pages which are require and also they are functioning well

**Comment by AYUSHJAISWAL12123** [comment]
@tushargupta1504 please assign it to me i can make all pages you just have to tell me the contents for the pages

**Comment by sambedan1** [comment]
please assign to me i have a great knowledge about it

**Comment by Antima2004** [comment]
please assign this to me.

**Comment by masabinhok** [comment]
Hi there!

I have resolved the navigation issue in the nearby.html file by updating the links to ensure they point correctly to the homepage and other sections. I have submitted a Pull Request for this fix.

Could you kindly assign me to this issue and accept my PR request?

Thank you!

**Comment by LavishaMhjn1910** [comment]
Hi there Please assign this task to me

**Comment by BhavikaPachauri** [comment]
Assign me

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue , as I have a strong background in CSS and HTML. Please assign me under GSSOC'24 extended and level 2 atleast.
