### ISSUE TITLE
Font Size of the message Welcome to a World of personalised healthcare is too small

### ISSUE THREAD

**Issue by ahinagangopadhyay** [tushargupta1504/Medical-Website#112]
![Screenshot (244)](https://github.com/user-attachments/assets/3e1b7a50-b309-4465-a083-6e9af7a54c05)

I want to change the font size so that the text becomes readable and the ui is improved.
Please assign me this issue for Hacktoberfest 2024 .

**Comment by Ishika-codeit** [comment]
hey kindly assign this issue to me...
i try my best to make it more responsive..
changing font family and font size with various text properties...
