### ISSUE TITLE
Homepage navbar is messed up

### ISSUE THREAD

**Issue by alvin-dennis** [tushargupta1504/Medical-Website#122]
The navbar in the homepage is messed up. Allow me to fix it. Hacktoberfest

**Comment by Ajdecoder** [comment]
I would like to work on it to beautify it and make it responsive

**Comment by saurabhsagar99** [comment]
Navbar is quite messed up and it's not responsive, I will fixed the navbar in addition I will add hamburger button on it.So please assign this task to me
