### ISSUE TITLE
Improving the services section

### ISSUE THREAD

**Issue by riyarane46** [tushargupta1504/Medical-Website#128]
@tushargupta1504 
i would like to improve the styling of service section .
i believe i can do this task efficiently as i have a strong hold over css styling and have completed many projects.
please assign me this task under GSSoC24 extd and hactoberfest , also assign the level label.

**Comment by LavishaMhjn1910** [comment]
I would like to improve the styling of the service section.
I believe I can do this task efficiently as I have a strong hold over CSS styling and have completed many projects.
please assign me this task
