### ISSUE TITLE
Blog Section

### ISSUE THREAD

**Issue by Manvi-Nayak** [tushargupta1504/Medical-Website#131]
The Blog section of the site is not working or there might be no blogs currently. Please assign this task to me under GSSOC and hacktoberfest tag, I will add some good blogs for the user to read and interact with greatly.

**Comment by Rashmi885** [comment]
Pls assign this task to me under GSSOC as I have prior experience on this.

**Comment by Siddhant432** [comment]
I can do this task , pls assign this task to me under gssoc .

**Comment by Siddhant432** [comment]
I have made it , review it pls.
![Screenshot (477)](https://github.com/user-attachments/assets/87585058-6468-46f7-bc95-c376d2178fe4)
![Screenshot (478)](https://github.com/user-attachments/assets/e1f9e9b2-5f15-4579-b14f-0ce8d7112d5d)

**Comment by Siddhant432** [comment]
pls reply @tushargupta1504 .
