### ISSUE TITLE
Improve 'Nearby Section'

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [tushargupta1504/Medical-Website#153]
I want to make 'nearby section' more user friendly as the current structure is like this:
![Screenshot 2024-10-03 144838](https://github.com/user-attachments/assets/896c8031-d4f1-46d2-b597-772f03968a96)
which is surely not a user friendly more like a pdf file to read.
Please assign me this task .

**Comment by tushargupta1504** [comment]
ok
