### ISSUE TITLE
adding carousel effect at top

### ISSUE THREAD

**Issue by YooAshu** [tushargupta1504/Medical-Website#16]
the top image is static adding a carousel will be very good for user experience

**Comment by ayush-py-c** [comment]
I hope you're doing well! I’d like to work on the issue adding carousel effect at top #16 . Could you please assign it to me? I believe I can make meaningful progress

**Comment by YooAshu** [comment]
please check PR #120

**Comment by YooAshu** [comment]
@ayush-py-c bro don't get me wrong but u should write issues by yourself and work on that , make PR for issues which are left for a long time 🫠 @tushargupta1504
