### ISSUE TITLE
improving contact us section

### ISSUE THREAD

**Issue by YooAshu** [tushargupta1504/Medical-Website#17]
currently the contact us section doesn't look good adding some styles and animation will be useful

**Comment by AbhinabPalei** [comment]
can you assign me this issue

**Comment by rutikakengal** [comment]
I liked to work on contat us section for the Website Assigm me

**Comment by mansi066** [comment]
I want to work on this issue please assign me

**Comment by YooAshu** [comment]
@mansi066 yeah u should be assigned for this 👍
