### ISSUE TITLE
improving the responsiveness for the mobile

### ISSUE THREAD

**Issue by sahhoArjun097** [tushargupta1504/Medical-Website#19]
i can fix the responsiveness for the mobile screen .
![Screenshot 2024-10-01 215241](https://github.com/user-attachments/assets/830668b7-dabe-4028-b941-66175eec29cf)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant .

**Comment by sambedan1** [comment]
assign this to me
