### ISSUE TITLE
adding a go to top floating button

### ISSUE THREAD

**Issue by YooAshu** [tushargupta1504/Medical-Website#23]
at the bottom right of website there should be a go to top button on clicking the user will be scrolled to top

**Comment by ayush-py-c** [comment]
I hope you're doing well! I’d like to work on the issue adding a go to top floating button #23 . Could you please assign it to me? I believe I can make meaningful progress

**Comment by Devanshu1603** [comment]
please assign it to me . i want to fix this isssue.

**Comment by YooAshu** [comment]
@tushargupta1504 given in the rules you should assign one task to only one contributor the one who wrote the issue if he can't do the task then assign it to others , hope you understand

**Comment by YooAshu** [comment]
@tushargupta1504 please check the PR #69 regarding this issue
