### ISSUE TITLE
Title of the webpage needs to be changed

### ISSUE THREAD

**Issue by Sameeratweb** [tushargupta1504/Medical-Website#25]
![Screenshot 2024-10-01 223640](https://github.com/user-attachments/assets/23771727-8419-498a-bbdf-f87e30110ab7)
as it is showing the custom title, Title of the webpage needs to be changed.
I would like to work on this  issue please allow me with this issue and relevant tags under GSSoC'24-Extd

**Comment by tushargupta1504** [comment]
pls check already opned issue
