### ISSUE TITLE
Contact Us page is changed and it's looks very worse.

### ISSUE THREAD

**Issue by VinodKumarN1** [tushargupta1504/Medical-Website#261]
![Screenshot_20241006_234043](https://github.com/user-attachments/assets/a447a6cf-5301-4fa0-bec5-a376c6a39bd1)

I don't know who made it or assigned for that please assign me i'll work on it, making it more suitable for the website theme.

**Comment by genomecrafter** [comment]
I see this issue hasn’t been assigned yet. I’d be happy to take it on and align the solution with the website theme. Could you please assign it to me? Thank you!

**Comment by 2027Anamika** [comment]
Task to be done
 I want to redesign the layout  for better readability.
Add sections for FAQs or common inquiries.
Please  assign this issue to me @tushargupta1504
