### ISSUE TITLE
I want add a new section OUR SPECIAL DOCTORS in the form of cards .Please add gssoc-ext and hactoberfest label to the issue.

### ISSUE THREAD

**Issue by sonakshi2410** [tushargupta1504/Medical-Website#28]
Proposed solution- Each card will contain:
Doctor's Image
Name
Specialization
Contact Details
Social Media Info 
This section will enhance the user experience by showcasing the medical team in an organized and engaging way.
This section will be added below WHY SHOULD YOU CHOOSE US section.

**Comment by Siddhant432** [comment]
I have made this. Pls review it.
![Screenshot (473)](https://github.com/user-attachments/assets/4a006e8a-348d-4d92-b491-a109fa9d52bc)

**Comment by chmp0940** [comment]
i want to add a new section in more good way pls assign it to me

**Comment by mansi066** [comment]
I can made this with more information's please assign me
