### ISSUE TITLE
Improvement in Contact Us  Section

### ISSUE THREAD

**Issue by Ranj8521Kumar** [tushargupta1504/Medical-Website#281]
The current implementation of the Contact Us page has an issue where the input fields do not clear, I want to tackle this issue, Please assign this task to me, as I am eager to contribute to the project during this GSSoC and Hacktoberfest. I believe these enhancements will be beneficial for our users and improve the overall functionality of the page.

![image](https://github.com/user-attachments/assets/59f8eaed-9911-48e2-8a6b-5ed97ff27d9a)

**Comment by tushargupta1504** [comment]
Kindly look for another issues 
It is completed already
