### ISSUE TITLE
Adding Contributor Image Badges in Read Me file

### ISSUE THREAD

**Issue by Muskan-bhatt249** [tushargupta1504/Medical-Website#283]
![Screenshot 2024-10-07 194813](https://github.com/user-attachments/assets/1e6ae481-cdae-470c-aab1-e8e0d00e4c2d)
I can add a section in Read Me that shows Contributors Image badges like this, as a token of thanks to the contributors.

**Comment by tushargupta1504** [comment]
issue already exist kindly go through the previously opened issues
