### ISSUE TITLE
[bug] Image Containers image Overlapping/Overflowing

### ISSUE THREAD

**Issue by akash70629** [tushargupta1504/Medical-Website#303]
**Description:**

Image containers overlap/overflow each other on hover, causing visual distortion and layout issues.

**Steps to Reproduce:**

- Open the webpage.
- Navigate to the section with image containers.
- Hover on them and observe the image containers.

![image](https://github.com/user-attachments/assets/078f3e92-44a8-4b81-b361-63fac12bf747)

**Expected Result:**

Image containers should be displayed adjacent to each other, without overlapping.

**Actual Result:**

Image containers overlap/overflow with each other.

**Comment by HarshKumar1121** [comment]
please assign this issue to me i will fix this within hours after assigning.
