### ISSUE TITLE
Dark Mode changes and navbar navigation

### ISSUE THREAD

**Issue by saumyayadav25** [tushargupta1504/Medical-Website#420]
### 1) No navbar in book you appointment page, it makes it difficult for user to navigate back to home or other pages. Atleast a single back to home button should be there.
<img width="1267" alt="Screenshot 2024-10-13 at 3 05 02 PM" src="https://github.com/user-attachments/assets/e4a7e2df-d250-4b3c-993e-7d7a24aef720">

### Text not visible clearly in dark mode
<img width="1265" alt="Screenshot 2024-10-13 at 3 06 58 PM" src="https://github.com/user-attachments/assets/cd0d0025-7444-4ac5-b8bc-5e969292adf0">

### Text not at at all visible in dark mode. Text color changed to white on switching to dark theme.
<img width="1288" alt="Screenshot 2024-10-13 at 3 07 37 PM" src="https://github.com/user-attachments/assets/8b11c0c3-5acb-441e-8e81-2b34133d6a73">

### Text visible only in light mode for doctors contact
<img width="1350" alt="Screenshot 2024-10-13 at 3 07 47 PM" src="https://github.com/user-attachments/assets/bc86f640-0dbf-4054-80de-9ac32410b3e9">

### Not enough space at the bottom of footer
<img width="1397" alt="Screenshot 2024-10-13 at 3 08 06 PM" src="https://github.com/user-attachments/assets/9073ed80-522a-44e3-a720-e1e0ca949eab">

**Comment by saumyayadav25** [comment]
@tushargupta1504 kindly review this issue and do let me know if any or all of the tasks will be assigned to me?

**Comment by Swyom** [comment]
give me a chance to solve the issues .

**Comment by saumyayadav25** [comment]
@tushargupta1504 kindly review this issue and do let me know if any of task is assigned to me?
