### ISSUE TITLE
doctor login page and admin login page are not linked

### ISSUE THREAD

**Issue by aishwaria12** [tushargupta1504/Medical-Website#431]
The doctor login page and admin login page are not linked to the Index File. So, the doctor login page and admin log in page is not working properly.
![Screenshot 2024-10-14 103356](https://github.com/user-attachments/assets/2551f55c-7570-46e4-b7a8-3def8cc8a1bf)
![image](https://github.com/user-attachments/assets/ece77fac-8095-449b-b4b3-f6c902241cdf)

 Could you please assign me the work? @tushargupta1504

**Comment by shauryaq05** [comment]
Please assign this work to me
