### ISSUE TITLE
[bug] Navbar Text Misalignment and Overlapping Issues in Dark Mode

### ISSUE THREAD

**Issue by Ankul8471** [tushargupta1504/Medical-Website#445]
The navigation bar has multiple issues affecting usability. The text is not aligned accurately, causing elements to appear out of place. Additionally, in some areas, the text overlaps, making the options hard to read and interact with. These problems are more prominent when dark mode is enabled, further impacting the user experience.

Steps to Reproduce:

Open the website.
Switch to dark mode.
Notice the misalignment and overlapping text in the navbar, particularly near elements like "Schedule and Remind" toggle and "Admin Login."
Expected Behavior:
The navbar text should be properly aligned without any overlap, and all elements should be easily readable and accessible in both light and dark modes.

Suggested Solution:

Correct the alignment of the navbar elements to ensure they are uniformly placed.
Fix the overlapping issue by adjusting the layout or spacing between elements.
Verify that all text is fully readable and properly contrasted in 
![mmmm](https://github.com/user-attachments/assets/3bcca356-0014-4e07-93dd-3d64d486ee97)

**Comment by Ankul8471** [comment]
@tushargupta1504   Hello sir i would like to work on it please assign me

**Comment by Roshansuthar1105** [comment]
Dear Sir , I made changes on this issue , kindly check.
