### ISSUE TITLE
making address ,call us now ,mail us now section more engaging.

### ISSUE THREAD

**Issue by Rish6392** [tushargupta1504/Medical-Website#499]
![Screenshot 2024-10-18 102033](https://github.com/user-attachments/assets/a75cb59c-d77f-4965-9e5e-ea5d052d27cb)
i wanna make this section look attractive.

please assign these issue to me @tushargupta1504 .

**Comment by tushargupta1504** [comment]
change the email to tusharg1504@gmail.com too
