### ISSUE TITLE
IMPROVED USER INTERFACE OF THE FOOTER✨

### ISSUE THREAD

**Issue by shriyadindi** [tushargupta1504/Medical-Website#502]
I would like to enhance the user interface of the footer, kindly assign me the task.

**Comment by tushargupta1504** [comment]
Kindly explain in detail , what changes do you want to make , and why the old - one is not good

**Comment by shriyadindi** [comment]
I would like to realign the footer elements as they are unordered and modify the CSS styling
![Screenshot 2024-10-18 212043](https://github.com/user-attachments/assets/5e1f5ffe-c9e4-430c-a108-e6b42fcc9bc0)
