### ISSUE TITLE
CSS STYLING OF THE OUR COMMITMENT SECTION✨

### ISSUE THREAD

**Issue by shriyadindi** [tushargupta1504/Medical-Website#503]
I would like to enhance the user interface of the Our commitment section, kindly assign me the task.

**Comment by tushargupta1504** [comment]
Kindly explain in detail , what changes do you want to make , and why the old - one is not good

**Comment by tushargupta1504** [comment]
K

**Comment by shriyadindi** [comment]
@tushargupta1504 the our commitment section is oddly aligned, I would like to enhance the overall section by modifying the User interface by making it more attractive
![Screenshot 2024-10-18 212231](https://github.com/user-attachments/assets/907fcd95-2f96-4c6b-8cbe-aae5931c5358)
