### ISSUE TITLE
🐞BUG: APPEARANCE OF THE TOGGLE BAR IN THE CONTACT US MENU

### ISSUE THREAD

**Issue by shriyadindi** [tushargupta1504/Medical-Website#504]
There is glitch in the contact form, kindly assign me the task

**Comment by tushargupta1504** [comment]
explain in detail

**Comment by shriyadindi** [comment]
The send message button overlaps both the contact form and the map and the contact form is not appealing, I would like to work on it, kindly assign me the task.
![Screenshot 2024-10-18 212430](https://github.com/user-attachments/assets/1acd4d0a-dec1-43fd-893c-3b3139e60eea)
