### ISSUE TITLE
want to improve the footer section

### ISSUE THREAD

**Issue by Ash182004** [tushargupta1504/Medical-Website#507]
![image](https://github.com/user-attachments/assets/6e73bfe2-2707-4589-8f5a-506e7cb6ac74)
this section is very hotchpotch kind of, the font size and styling of paragraph is not good, i want to improve it 
@tushargupta1504 plz assign me this issue

**Comment by kiinshuk** [comment]
Hi @tushargupta1504 , I'd like to help with this issue. Could you please assign it to me?

**Comment by GyanaPrakashSahoo7853** [comment]
@tushargupta1504  I would like to work on this issue can you please assign me this task

**Comment by GyanaPrakashSahoo7853** [comment]
@tushargupta1504 please review my pull request i have fixed the conflict that happened previously
