### ISSUE TITLE
Submit button Functionality

### ISSUE THREAD

**Issue by Devanshu1603** [tushargupta1504/Medical-Website#51]
input feild in contact us section are not getting cleared after submiting it. please assign it me under gssoc ext level so that i can contribute to it

**Comment by simmi-verma** [comment]
I would like to work on this. please assign to me. first time I am contributing in gssoc-ext 24.

**Comment by simmi-verma** [comment]
Sir, I have solved this problem. Please merge it on GitHub.

**Comment by simmi-verma** [comment]
hello sir, please add gssoc level.

**Comment by Devanshu1603** [comment]
it must be a first come first issue.

**Comment by simmi-verma** [comment]
My PR is already merged.

**Comment by simmi-verma** [comment]
Sir, please add level.
