### ISSUE TITLE
Navbar , contact and testimonital

### ISSUE THREAD

**Issue by Dipeshdahiya** [tushargupta1504/Medical-Website#54]
@tushargupta1504  I seen your design very carefully and noticed very irregular designing , the navbar transition , the testimonial is not looking very much user friendly and as well as the contact form should be in the mid with proper margin and padding , 
Please assign these issues to me i will make sure to make your landing page look good as much as possible

**Comment by riyarane46** [comment]
hii @tushargupta1504  i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd and hactoberfest24.
