### ISSUE TITLE
[Bug] Remove the discord link section in the readme

### ISSUE THREAD

**Issue by Aditya-NV-06** [tushargupta1504/Medical-Website#549]
The link in the discord section of the readme is not the right link for this repo.  Make changes immediately. Add the greeting workflows for the contributors.

**Comment by aditya-bhaumik** [comment]
@tushargupta1504 hi i am the owner of the discord server mentioned in your readme 

Please remove it from your readme as the contributors are getting confused

**Comment by Aditya-NV-06** [comment]
Made a pr for this issue #547

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by Aditya-NV-06** [comment]
> I would like to work on this issue. Could you please assign me this task
  This issue has been solved 1 month ago.
