### ISSUE TITLE
Enhancing Functionalities of navbar

### ISSUE THREAD

**Issue by Sameeratweb** [tushargupta1504/Medical-Website#55]
By clicking on items in the navbar, the user will be redirected to specific sections of the webpage.

i would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by riyarane46** [comment]
hii @tushargupta1504  i believe i can do this task efficiently as i have a strong hold over css styling. could you please assign me this task under GSSoC24 extd and hactoberfest24.

**Comment by Aditya-NV-06** [comment]
i made a small change for the navigation of the section and submitted pr no #105

**Comment by riyarane46** [comment]
@tushargupta1504 can you also add label of level to this issue

**Comment by riyarane46** [comment]
@tushargupta1504 
please review the pull request
 can you also add label of level to this issue .
