### ISSUE TITLE
Home Page Improvement

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [tushargupta1504/Medical-Website#6]
I found areas to improve on the homepage, including alignment, fonts, and colors.

 The main focus will be on the card and form sections:

-  The submit button has a typo "middle" which i would recorrect.
-  I'll also ensure every card includes all necessary specifications with necessary CSS features ( like transitions) when hovered.

please assign this task to me.

**Comment by Shukla000** [comment]
I would like to work over the form in the home page . Please assign me the task .
Thank you.

**Comment by Adarsh-Chaubey03** [comment]
Completed the assigned task  created a PR #152   for it.  Please review it

**Comment by gayathri1908** [comment]
I would like to work for the home page improvement.Please assign this to me
