### ISSUE TITLE
"Get started" button doesn't work

### ISSUE THREAD

**Issue by poorvikaa08** [tushargupta1504/Medical-Website#60]
ISSUE:
* When a user clicks on "Get started" button the page is irresponsive and doesn't redirect to the sign-in page.
* No navigation occurs, and the user remains on the homepage.

Improvements:
* Adding a user-login/ sign-in page for better usage.

Screenshot 📸 
https://github.com/user-attachments/assets/9cf2c235-3bd0-4ff0-ba61-e4cf4b44d695

I would like to work on this issue by creating a sign-in page that is redirected when the user clicks on the "Get Started" button
@tushargupta1504 would you assign this issue to me under **gssoc24 extd** and **hacktoberfest** with the appropriate level?
Thank you, looking forward to contribute.

**Comment by Rashmi885** [comment]
Interested to work on this project as a beginner, pls assign to me.

**Comment by vararaghu002** [comment]
I would like to address this issue by adding a sign-up form after clicking on 'Get Started, making more interactive and responsive for the user
please assign this issue to me
