### ISSUE TITLE
improve font style of website

### ISSUE THREAD

**Issue by adityakalburgi** [tushargupta1504/Medical-Website#66]
Hi!
I'd like to improve the website by adding a new, appealing font. Could you please assign this issue to me? Thanks!

**Comment by simmi-verma** [comment]
I would like to work on this. please assign to me. first time I am contributing in gssoc-ext 24.

**Comment by Ishika-codeit** [comment]
hey...
this is must as font leads first impression on any website kindly assign it to me...

**Comment by BhavikaPachauri** [comment]
I want to work on this issue
