### ISSUE TITLE
Project Enhancements and New Feature Implementation

### ISSUE THREAD

**Issue by snehhhcodes** [tushargupta1504/Medical-Website#7]
Hello Tushar,

I hope this communication finds you in good health. I want to address a few flaws I saw and would like to contribute to the project:

Description of Issues:

1.) Project name and favicon missing: As of right now, the project is just shown as "Document" and lacks a favicon.
2.) Navigation Links That Don't Work: There is no navigation functionality when you click on the navigation bar because it doesn't lead to any pages.

Proposed Solutions:

1.) Updates to the Project Name and Favicon: To give the project a distinct identity, I can design and apply a project logo in addition to a favicon and name.

2.) Navigation Enhancement: In order to make sure that users can reach the intended pages, I will look at the navigation links and make the required adjustments.

3.) Locate Nearby Hospitals and Pharmacies: I propose adding a feature that allows users to find nearby hospitals and pharmacies. While I’m not yet proficient with APIs, I can implement direct links to reputable hospitals in specific areas, such as Delhi, which will open maps for users.

If you find this proposal suitable, I would appreciate it if you could assign these tasks to me.

**Comment by CHIHNITA-REDDY-B** [comment]
Please assign this issue to me aswell I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevan.

**Comment by CHIHNITA-REDDY-B** [comment]
yeah sure will work on it
Thank you for assigning

**Comment by snehhhcodes** [comment]
@tushargupta1504 Hey, u havent labelled this issue yet it would be great if you can tushar!!
