### ISSUE TITLE
Fix Navbar to Stay at the Top While Scrolling Down

### ISSUE THREAD

**Issue by Shiv13jm** [tushargupta1504/Medical-Website#70]
![Screenshot 2024-10-02 143610](https://github.com/user-attachments/assets/d84bb9b4-e7eb-4d51-8724-ff01094d773e)

The current implementation of the navbar does not remain fixed at the top of the page when the user scrolls down. This can affect the user experience as the navigation options are not readily accessible. We need to update the navbar to ensure it stays fixed at the top of the viewport during scrolling.
### 
Expected Behavior:
The navbar should remain fixed at the top of the viewport, regardless of the scroll direction (up or down).

### Actual Behavior:
The navbar is visible when scrolling up but disappears when scrolling down.

Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

**Comment by Pratikpawar13** [comment]
@tushargupta1504 I would like work on this repo.
Please assign me this to solve this issue.

**Comment by ayush-py-c** [comment]
![image](https://github.com/user-attachments/assets/cb57c0ab-9f4c-4b9d-8efc-4bd5fa7f18bb)
Added a fix back to top button
