### ISSUE TITLE
Getting the contact section to look good and work!

### ISSUE THREAD

**Issue by SAMluci666** [tushargupta1504/Medical-Website#76]
- The current contact section does not look look good for both UI and UX.
- No Form Validations --> Need to add form Validations
- Improve the UI of the Contact sections as well as make the page scroll to contact section when clicked in navigation bar.

**Comment by SAMluci666** [comment]
Please assign this issue to me under GSSOC24Extended and Hacktoberfest. Thanks!

**Comment by Antima2004** [comment]
please assign this to me
