### ISSUE TITLE
Implement login and sign up functionality

### ISSUE THREAD

**Issue by Ankitha2130** [tushargupta1504/Medical-Website#79]
I will work on the sign up and login functionality that allows users to login if they already exists, and if they are new user allows them to sign up.
Please assign this issue to me.
Please add the hacktoberfest, gssoc-extd, and the level label.

**Comment by spacedust26** [comment]
Hey @tushargupta1504,
I'd like to work on making a login and signup page pertaining to the theme of the website.
Would be excited to start working on it after being assigned!
Thankyou.

**Comment by Dipit12** [comment]
HI @tushargupta1504 i would love to contribute on this issue, kindly make me the assignee so that i can start working on this as soon as possible

**Comment by akshatshukla13** [comment]
@tushargupta1504 
I would like to implement both login and signup functionality with JWT integration.
Also this will be my first contribution in hacktoberfest. Will be fun!

**Comment by LavishaMhjn1910** [comment]
Hi @tushargupta1504 I would like to contribute to this issue Please assign this to me

**Comment by Harshitraaaj** [comment]
since i have already worked on this issue on another project and successfully implemented login/signup functionality . I think i can solve your problem ASAP. assign this role to me .

**Comment by supreetkaursareen** [comment]
@tushargupta1504  can you please assign this to me?

**Comment by Harshitraaaj** [comment]
@tushargupta1504 I have completed Login/signup functionality .

Here is the video link : https://drive.google.com/file/d/14sGmHDF_c2j-TWenl4op_opaYtjTbokj/view?usp=drivesdk
