### ISSUE TITLE
Add code of conduct.md

### ISSUE THREAD

**Issue by kartikey369-ind** [tushargupta1504/Medical-Website#82]
I want to add code of conduct.md

**Comment by kartikey369-ind** [comment]
if possible can you add hacktoberfest lable

**Comment by Shiva-Bajpai** [comment]
Added the code of conduct

**Comment by kartikey369-ind** [comment]
done my work https://github.com/tushargupta1504/Medical-Website/pull/154

**Comment by rivercory** [comment]
@kartikey369-ind It's probably a good idea to close this issue.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
and add the gssoc-ext label
