### ISSUE TITLE
Better display of pictures

### ISSUE THREAD

**Issue by S7viks** [tushargupta1504/Medical-Website#91]
Can add a rolling carousel to the website to display the pictures 
![image](https://github.com/user-attachments/assets/d37ec093-f21e-4702-9d93-ca260e8cfda8)

Please add gssoc-extnd label along with level label

**Comment by sambedan1** [comment]
assign this to me

**Comment by shreyajaiswal17** [comment]
Hey @tushargupta1504 can you assign this to me.

**Comment by S7viks** [comment]
@tushargupta1504 please assign this to me

**Comment by Kavish-Paraswar** [comment]
I would like to work on this issue , as I have a strong background in CSS and HTML. Please assign me under GSSOC'24 extended and level 2 atleast.
