### ISSUE TITLE
Adding Blogs section 

### ISSUE THREAD

**Issue by aadhi-i** [tushargupta1504/Medical-Website#92]
I would like to work on adding a blogs section since it is there on the navbar and I can also link up the Services section and contact section along with that. Please assign this to me under gssoc ext with specific level and hacktoberfest. @tushargupta1504 

![Screenshot 2024-10-02 182947](https://github.com/user-attachments/assets/48ff150c-297d-4a4d-8713-3d458329218e)

**Comment by itzkushagra** [comment]
Hi, I would like to take up this task. I will follow the code of conduct properly and fulfill the requirement of the assigned task accurately. I would request you to assign me this issue under the label Hacktoberfest along with appropriate level. It would mean a lot

**Comment by simmi-verma** [comment]
i would like to work on this . please assign to me.
