### ISSUE TITLE
Add personalized logo

### ISSUE THREAD

**Issue by shreyad2806** [tushargupta1504/Medical-Website#94]
I can add personalized logo for your website to make it look more professional and asthetic.
Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.

**Comment by shreyajaiswal17** [comment]
Hey I too can add a personalized logo for your website .
Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.

**Comment by Siddhant432** [comment]
I can design a logo for this website

**Comment by SHUBHAG100520** [comment]
I can too work on designing a logo .can you assign it to me .

**Comment by tushargupta1504** [comment]
@shreyajaiswal17 assigned it to you
