### ISSUE TITLE
Add a Mouse followers

### ISSUE THREAD

**Issue by swamimalode07** [tushargupta1504/Medical-Website#95]
Kindly assign me the task to add a Mouse follower to this website under hactoberfest

**Comment by tushargupta1504** [comment]
explain in brief

**Comment by swamimalode07** [comment]
When you move the cursor it will have a mouse folllower like this 
![image](https://github.com/user-attachments/assets/71095bf6-32e9-47e7-9934-0f38f4b36a78)
When you move cursor , the mouse follower will follow the movement
