### ISSUE TITLE
Addition of a Health GPT chatbot in the website

### ISSUE THREAD

**Issue by Dipit12** [tushargupta1504/Medical-Website#98]
Hi, @tushargupta1504 
I think the website is too mediocre to be honest, and needs a lot of improvements, at this point of time its only a frontend webiste, i think addition of a chatbot to the website would improve the overall appeal of the website. 
Kindly open this issue and assign it to me

**Comment by Dipit12** [comment]
@tushargupta1504 can you also add the hacktoberfest label since i am participating in both gssoc-ext and hactoberfest

**Comment by sambedan1** [comment]
please assign this task to me

**Comment by Dipit12** [comment]
@tushargupta1504 
This is how the chatbot looks like
Ignore the video quality since i had to compress the screen recording video

https://github.com/user-attachments/assets/e8c254f9-2dda-4b53-bfa8-4928fb672371

**Comment by gayathri1908** [comment]
heyy @tushargupta1504 I think its only a frontend website. I think addition of a chatbot helps this a lot so I want to work on this.Please assign this take to me.Thank you!
